2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Configure stats pid to 418860
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Loading settings from /home/jesse/.config/wandb/settings
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Loading settings from /home/jesse/WGU/ML DevOps - D501/Udacity/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/genre_classification/check_data/wandb/settings
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_group': 'dev', 'project': 'genre_classification'}
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-12-08 18:24:55,062 WARNING MainThread:418860 [wandb_setup.py:_flush():76] Could not save program above cwd: /home/jesse/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/home/jesse/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest', 'program': '/home/jesse/anaconda3/envs/mlflow-60000e2b97642ccc38c7a9ee503977f0abd54819/bin/pytest'}
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_init.py:_log_setup():526] Logging user logs to /home/jesse/WGU/ML DevOps - D501/Udacity/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/genre_classification/check_data/wandb/run-20241208_182455-ft01ttkj/logs/debug.log
2024-12-08 18:24:55,062 INFO    MainThread:418860 [wandb_init.py:_log_setup():527] Logging internal logs to /home/jesse/WGU/ML DevOps - D501/Udacity/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/genre_classification/check_data/wandb/run-20241208_182455-ft01ttkj/logs/debug-internal.log
2024-12-08 18:24:55,063 INFO    MainThread:418860 [wandb_init.py:init():566] calling init triggers
2024-12-08 18:24:55,063 INFO    MainThread:418860 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-12-08 18:24:55,063 INFO    MainThread:418860 [wandb_init.py:init():616] starting backend
2024-12-08 18:24:55,063 INFO    MainThread:418860 [wandb_init.py:init():620] setting up manager
2024-12-08 18:24:55,064 INFO    MainThread:418860 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-08 18:24:55,066 INFO    MainThread:418860 [wandb_init.py:init():628] backend started and connected
2024-12-08 18:24:55,069 INFO    MainThread:418860 [wandb_init.py:init():720] updated telemetry
2024-12-08 18:24:55,076 INFO    MainThread:418860 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-12-08 18:24:55,424 INFO    MainThread:418860 [wandb_run.py:_on_init():2262] communicating current version
2024-12-08 18:24:55,574 INFO    MainThread:418860 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.19.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-12-08 18:24:55,574 INFO    MainThread:418860 [wandb_init.py:init():804] starting run threads in backend
2024-12-08 18:24:56,090 INFO    MainThread:418860 [wandb_run.py:_console_start():2241] atexit reg
2024-12-08 18:24:56,091 INFO    MainThread:418860 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-12-08 18:24:56,091 INFO    MainThread:418860 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-12-08 18:24:56,091 INFO    MainThread:418860 [wandb_run.py:_redirect():2186] Redirects installed.
2024-12-08 18:24:56,091 INFO    MainThread:418860 [wandb_init.py:init():847] run started, returning control to user process
2024-12-08 18:25:06,726 WARNING MsgRouterThr:418860 [router.py:message_loop():77] message_loop has been closed
